/* soapH.h
   Generated by gSOAP 2.8.17r from YrElecarDetect.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 const char ** SOAP_FMAC4 soap_faultcode(struct soap *soap);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#ifndef soap_write_byte
#define soap_write_byte(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_byte(soap, data),0) || soap_put_byte(soap, data, "byte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef soap_read_byte
#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#ifndef soap_write_int
#define soap_write_int(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_int(soap, data),0) || soap_put_int(soap, data, "int", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef soap_read_int
#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Fault
#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Fault(soap, data),0) || soap_put_SOAP_ENV__Fault(soap, data, "SOAP-ENV:Fault", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Fault
#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Fault * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Fault * soap_new_SOAP_ENV__Fault(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Fault(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Fault * soap_new_req_SOAP_ENV__Fault(struct soap *soap) { struct SOAP_ENV__Fault *_p = soap_instantiate_SOAP_ENV__Fault(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Fault(soap, _p); } return _p; }

inline struct SOAP_ENV__Fault * soap_new_set_SOAP_ENV__Fault(struct soap *soap, char *faultcode, char *faultstring, char *faultactor, struct SOAP_ENV__Detail *detail, struct SOAP_ENV__Code *SOAP_ENV__Code, struct SOAP_ENV__Reason *SOAP_ENV__Reason, char *SOAP_ENV__Node, char *SOAP_ENV__Role, struct SOAP_ENV__Detail *SOAP_ENV__Detail) { struct SOAP_ENV__Fault *_p = soap_instantiate_SOAP_ENV__Fault(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Fault(soap, _p); _p->faultcode = faultcode; _p->faultstring = faultstring; _p->faultactor = faultactor; _p->detail = detail; _p->SOAP_ENV__Code = SOAP_ENV__Code; _p->SOAP_ENV__Reason = SOAP_ENV__Reason; _p->SOAP_ENV__Node = SOAP_ENV__Node; _p->SOAP_ENV__Role = SOAP_ENV__Role; _p->SOAP_ENV__Detail = SOAP_ENV__Detail; } return _p; }

inline void soap_delete_SOAP_ENV__Fault(struct soap *soap, struct SOAP_ENV__Fault *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Reason
#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Reason(soap, data),0) || soap_put_SOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Reason
#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Reason * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Reason * soap_new_SOAP_ENV__Reason(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Reason(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Reason * soap_new_req_SOAP_ENV__Reason(struct soap *soap) { struct SOAP_ENV__Reason *_p = soap_instantiate_SOAP_ENV__Reason(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Reason(soap, _p); } return _p; }

inline struct SOAP_ENV__Reason * soap_new_set_SOAP_ENV__Reason(struct soap *soap, char *SOAP_ENV__Text) { struct SOAP_ENV__Reason *_p = soap_instantiate_SOAP_ENV__Reason(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Reason(soap, _p); _p->SOAP_ENV__Text = SOAP_ENV__Text; } return _p; }

inline void soap_delete_SOAP_ENV__Reason(struct soap *soap, struct SOAP_ENV__Reason *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Detail
#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Detail(soap, data),0) || soap_put_SOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Detail
#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Detail * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Detail * soap_new_SOAP_ENV__Detail(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Detail(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Detail * soap_new_req_SOAP_ENV__Detail(struct soap *soap, int __type, void *fault) { struct SOAP_ENV__Detail *_p = soap_instantiate_SOAP_ENV__Detail(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Detail(soap, _p); _p->__type = __type; _p->fault = fault; } return _p; }

inline struct SOAP_ENV__Detail * soap_new_set_SOAP_ENV__Detail(struct soap *soap, char *__any, int __type, void *fault) { struct SOAP_ENV__Detail *_p = soap_instantiate_SOAP_ENV__Detail(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Detail(soap, _p); _p->__any = __any; _p->__type = __type; _p->fault = fault; } return _p; }

inline void soap_delete_SOAP_ENV__Detail(struct soap *soap, struct SOAP_ENV__Detail *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Code
#define soap_write_SOAP_ENV__Code(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Code(soap, data),0) || soap_put_SOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Code
#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Code * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Code * soap_new_SOAP_ENV__Code(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Code(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Code * soap_new_req_SOAP_ENV__Code(struct soap *soap) { struct SOAP_ENV__Code *_p = soap_instantiate_SOAP_ENV__Code(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Code(soap, _p); } return _p; }

inline struct SOAP_ENV__Code * soap_new_set_SOAP_ENV__Code(struct soap *soap, char *SOAP_ENV__Value, struct SOAP_ENV__Code *SOAP_ENV__Subcode) { struct SOAP_ENV__Code *_p = soap_instantiate_SOAP_ENV__Code(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Code(soap, _p); _p->SOAP_ENV__Value = SOAP_ENV__Value; _p->SOAP_ENV__Subcode = SOAP_ENV__Subcode; } return _p; }

inline void soap_delete_SOAP_ENV__Code(struct soap *soap, struct SOAP_ENV__Code *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Header
#define soap_write_SOAP_ENV__Header(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Header(soap, data),0) || soap_put_SOAP_ENV__Header(soap, data, "SOAP-ENV:Header", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Header
#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Header * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Header * soap_new_SOAP_ENV__Header(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Header(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Header * soap_new_req_SOAP_ENV__Header(struct soap *soap) { struct SOAP_ENV__Header *_p = soap_instantiate_SOAP_ENV__Header(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Header(soap, _p); } return _p; }

inline struct SOAP_ENV__Header * soap_new_set_SOAP_ENV__Header(struct soap *soap) { struct SOAP_ENV__Header *_p = soap_instantiate_SOAP_ENV__Header(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Header(soap, _p); } return _p; }

inline void soap_delete_SOAP_ENV__Header(struct soap *soap, struct SOAP_ENV__Header *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE_ns__DelCamera
#define SOAP_TYPE_ns__DelCamera (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__DelCamera(struct soap*, struct ns__DelCamera *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__DelCamera(struct soap*, const struct ns__DelCamera *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__DelCamera(struct soap*, const char*, int, const struct ns__DelCamera *, const char*);
SOAP_FMAC3 struct ns__DelCamera * SOAP_FMAC4 soap_in_ns__DelCamera(struct soap*, const char*, struct ns__DelCamera *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__DelCamera(struct soap*, const struct ns__DelCamera *, const char*, const char*);

#ifndef soap_write_ns__DelCamera
#define soap_write_ns__DelCamera(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__DelCamera(soap, data),0) || soap_put_ns__DelCamera(soap, data, "ns:DelCamera", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__DelCamera * SOAP_FMAC4 soap_get_ns__DelCamera(struct soap*, struct ns__DelCamera *, const char*, const char*);

#ifndef soap_read_ns__DelCamera
#define soap_read_ns__DelCamera(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__DelCamera(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct ns__DelCamera * SOAP_FMAC2 soap_instantiate_ns__DelCamera(struct soap*, int, const char*, const char*, size_t*);

inline struct ns__DelCamera * soap_new_ns__DelCamera(struct soap *soap, int n = -1) { return soap_instantiate_ns__DelCamera(soap, n, NULL, NULL, NULL); }

inline struct ns__DelCamera * soap_new_req_ns__DelCamera(struct soap *soap) { struct ns__DelCamera *_p = soap_instantiate_ns__DelCamera(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns__DelCamera(soap, _p); } return _p; }

inline struct ns__DelCamera * soap_new_set_ns__DelCamera(struct soap *soap, char *MsgXml) { struct ns__DelCamera *_p = soap_instantiate_ns__DelCamera(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns__DelCamera(soap, _p); _p->MsgXml = MsgXml; } return _p; }

inline void soap_delete_ns__DelCamera(struct soap *soap, struct ns__DelCamera *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__DelCamera(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__DelCameraResponse
#define SOAP_TYPE_ns__DelCameraResponse (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__DelCameraResponse(struct soap*, struct ns__DelCameraResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__DelCameraResponse(struct soap*, const struct ns__DelCameraResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__DelCameraResponse(struct soap*, const char*, int, const struct ns__DelCameraResponse *, const char*);
SOAP_FMAC3 struct ns__DelCameraResponse * SOAP_FMAC4 soap_in_ns__DelCameraResponse(struct soap*, const char*, struct ns__DelCameraResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__DelCameraResponse(struct soap*, const struct ns__DelCameraResponse *, const char*, const char*);

#ifndef soap_write_ns__DelCameraResponse
#define soap_write_ns__DelCameraResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__DelCameraResponse(soap, data),0) || soap_put_ns__DelCameraResponse(soap, data, "ns:DelCameraResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__DelCameraResponse * SOAP_FMAC4 soap_get_ns__DelCameraResponse(struct soap*, struct ns__DelCameraResponse *, const char*, const char*);

#ifndef soap_read_ns__DelCameraResponse
#define soap_read_ns__DelCameraResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__DelCameraResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct ns__DelCameraResponse * SOAP_FMAC2 soap_instantiate_ns__DelCameraResponse(struct soap*, int, const char*, const char*, size_t*);

inline struct ns__DelCameraResponse * soap_new_ns__DelCameraResponse(struct soap *soap, int n = -1) { return soap_instantiate_ns__DelCameraResponse(soap, n, NULL, NULL, NULL); }

inline struct ns__DelCameraResponse * soap_new_req_ns__DelCameraResponse(struct soap *soap) { struct ns__DelCameraResponse *_p = soap_instantiate_ns__DelCameraResponse(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns__DelCameraResponse(soap, _p); } return _p; }

inline struct ns__DelCameraResponse * soap_new_set_ns__DelCameraResponse(struct soap *soap, char *ResponseXml) { struct ns__DelCameraResponse *_p = soap_instantiate_ns__DelCameraResponse(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns__DelCameraResponse(soap, _p); _p->ResponseXml = ResponseXml; } return _p; }

inline void soap_delete_ns__DelCameraResponse(struct soap *soap, struct ns__DelCameraResponse *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__DelCameraResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__IfCamera
#define SOAP_TYPE_ns__IfCamera (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__IfCamera(struct soap*, struct ns__IfCamera *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__IfCamera(struct soap*, const struct ns__IfCamera *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__IfCamera(struct soap*, const char*, int, const struct ns__IfCamera *, const char*);
SOAP_FMAC3 struct ns__IfCamera * SOAP_FMAC4 soap_in_ns__IfCamera(struct soap*, const char*, struct ns__IfCamera *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__IfCamera(struct soap*, const struct ns__IfCamera *, const char*, const char*);

#ifndef soap_write_ns__IfCamera
#define soap_write_ns__IfCamera(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__IfCamera(soap, data),0) || soap_put_ns__IfCamera(soap, data, "ns:IfCamera", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__IfCamera * SOAP_FMAC4 soap_get_ns__IfCamera(struct soap*, struct ns__IfCamera *, const char*, const char*);

#ifndef soap_read_ns__IfCamera
#define soap_read_ns__IfCamera(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__IfCamera(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct ns__IfCamera * SOAP_FMAC2 soap_instantiate_ns__IfCamera(struct soap*, int, const char*, const char*, size_t*);

inline struct ns__IfCamera * soap_new_ns__IfCamera(struct soap *soap, int n = -1) { return soap_instantiate_ns__IfCamera(soap, n, NULL, NULL, NULL); }

inline struct ns__IfCamera * soap_new_req_ns__IfCamera(struct soap *soap) { struct ns__IfCamera *_p = soap_instantiate_ns__IfCamera(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns__IfCamera(soap, _p); } return _p; }

inline struct ns__IfCamera * soap_new_set_ns__IfCamera(struct soap *soap, char *MsgXml) { struct ns__IfCamera *_p = soap_instantiate_ns__IfCamera(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns__IfCamera(soap, _p); _p->MsgXml = MsgXml; } return _p; }

inline void soap_delete_ns__IfCamera(struct soap *soap, struct ns__IfCamera *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__IfCamera(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__IfCameraResponse
#define SOAP_TYPE_ns__IfCameraResponse (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__IfCameraResponse(struct soap*, struct ns__IfCameraResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__IfCameraResponse(struct soap*, const struct ns__IfCameraResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__IfCameraResponse(struct soap*, const char*, int, const struct ns__IfCameraResponse *, const char*);
SOAP_FMAC3 struct ns__IfCameraResponse * SOAP_FMAC4 soap_in_ns__IfCameraResponse(struct soap*, const char*, struct ns__IfCameraResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__IfCameraResponse(struct soap*, const struct ns__IfCameraResponse *, const char*, const char*);

#ifndef soap_write_ns__IfCameraResponse
#define soap_write_ns__IfCameraResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__IfCameraResponse(soap, data),0) || soap_put_ns__IfCameraResponse(soap, data, "ns:IfCameraResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__IfCameraResponse * SOAP_FMAC4 soap_get_ns__IfCameraResponse(struct soap*, struct ns__IfCameraResponse *, const char*, const char*);

#ifndef soap_read_ns__IfCameraResponse
#define soap_read_ns__IfCameraResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__IfCameraResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct ns__IfCameraResponse * SOAP_FMAC2 soap_instantiate_ns__IfCameraResponse(struct soap*, int, const char*, const char*, size_t*);

inline struct ns__IfCameraResponse * soap_new_ns__IfCameraResponse(struct soap *soap, int n = -1) { return soap_instantiate_ns__IfCameraResponse(soap, n, NULL, NULL, NULL); }

inline struct ns__IfCameraResponse * soap_new_req_ns__IfCameraResponse(struct soap *soap) { struct ns__IfCameraResponse *_p = soap_instantiate_ns__IfCameraResponse(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns__IfCameraResponse(soap, _p); } return _p; }

inline struct ns__IfCameraResponse * soap_new_set_ns__IfCameraResponse(struct soap *soap, char *ResponseXml) { struct ns__IfCameraResponse *_p = soap_instantiate_ns__IfCameraResponse(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns__IfCameraResponse(soap, _p); _p->ResponseXml = ResponseXml; } return _p; }

inline void soap_delete_ns__IfCameraResponse(struct soap *soap, struct ns__IfCameraResponse *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__IfCameraResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__AddCamera
#define SOAP_TYPE_ns__AddCamera (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__AddCamera(struct soap*, struct ns__AddCamera *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__AddCamera(struct soap*, const struct ns__AddCamera *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__AddCamera(struct soap*, const char*, int, const struct ns__AddCamera *, const char*);
SOAP_FMAC3 struct ns__AddCamera * SOAP_FMAC4 soap_in_ns__AddCamera(struct soap*, const char*, struct ns__AddCamera *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__AddCamera(struct soap*, const struct ns__AddCamera *, const char*, const char*);

#ifndef soap_write_ns__AddCamera
#define soap_write_ns__AddCamera(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__AddCamera(soap, data),0) || soap_put_ns__AddCamera(soap, data, "ns:AddCamera", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__AddCamera * SOAP_FMAC4 soap_get_ns__AddCamera(struct soap*, struct ns__AddCamera *, const char*, const char*);

#ifndef soap_read_ns__AddCamera
#define soap_read_ns__AddCamera(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__AddCamera(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct ns__AddCamera * SOAP_FMAC2 soap_instantiate_ns__AddCamera(struct soap*, int, const char*, const char*, size_t*);

inline struct ns__AddCamera * soap_new_ns__AddCamera(struct soap *soap, int n = -1) { return soap_instantiate_ns__AddCamera(soap, n, NULL, NULL, NULL); }

inline struct ns__AddCamera * soap_new_req_ns__AddCamera(struct soap *soap) { struct ns__AddCamera *_p = soap_instantiate_ns__AddCamera(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns__AddCamera(soap, _p); } return _p; }

inline struct ns__AddCamera * soap_new_set_ns__AddCamera(struct soap *soap, char *MsgXml) { struct ns__AddCamera *_p = soap_instantiate_ns__AddCamera(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns__AddCamera(soap, _p); _p->MsgXml = MsgXml; } return _p; }

inline void soap_delete_ns__AddCamera(struct soap *soap, struct ns__AddCamera *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__AddCamera(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__AddCameraResponse
#define SOAP_TYPE_ns__AddCameraResponse (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__AddCameraResponse(struct soap*, struct ns__AddCameraResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__AddCameraResponse(struct soap*, const struct ns__AddCameraResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__AddCameraResponse(struct soap*, const char*, int, const struct ns__AddCameraResponse *, const char*);
SOAP_FMAC3 struct ns__AddCameraResponse * SOAP_FMAC4 soap_in_ns__AddCameraResponse(struct soap*, const char*, struct ns__AddCameraResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__AddCameraResponse(struct soap*, const struct ns__AddCameraResponse *, const char*, const char*);

#ifndef soap_write_ns__AddCameraResponse
#define soap_write_ns__AddCameraResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__AddCameraResponse(soap, data),0) || soap_put_ns__AddCameraResponse(soap, data, "ns:AddCameraResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__AddCameraResponse * SOAP_FMAC4 soap_get_ns__AddCameraResponse(struct soap*, struct ns__AddCameraResponse *, const char*, const char*);

#ifndef soap_read_ns__AddCameraResponse
#define soap_read_ns__AddCameraResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__AddCameraResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct ns__AddCameraResponse * SOAP_FMAC2 soap_instantiate_ns__AddCameraResponse(struct soap*, int, const char*, const char*, size_t*);

inline struct ns__AddCameraResponse * soap_new_ns__AddCameraResponse(struct soap *soap, int n = -1) { return soap_instantiate_ns__AddCameraResponse(soap, n, NULL, NULL, NULL); }

inline struct ns__AddCameraResponse * soap_new_req_ns__AddCameraResponse(struct soap *soap) { struct ns__AddCameraResponse *_p = soap_instantiate_ns__AddCameraResponse(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns__AddCameraResponse(soap, _p); } return _p; }

inline struct ns__AddCameraResponse * soap_new_set_ns__AddCameraResponse(struct soap *soap, char *ResponseXml) { struct ns__AddCameraResponse *_p = soap_instantiate_ns__AddCameraResponse(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns__AddCameraResponse(soap, _p); _p->ResponseXml = ResponseXml; } return _p; }

inline void soap_delete_ns__AddCameraResponse(struct soap *soap, struct ns__AddCameraResponse *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__AddCameraResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__GetServerStatus
#define SOAP_TYPE_ns__GetServerStatus (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__GetServerStatus(struct soap*, struct ns__GetServerStatus *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__GetServerStatus(struct soap*, const struct ns__GetServerStatus *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__GetServerStatus(struct soap*, const char*, int, const struct ns__GetServerStatus *, const char*);
SOAP_FMAC3 struct ns__GetServerStatus * SOAP_FMAC4 soap_in_ns__GetServerStatus(struct soap*, const char*, struct ns__GetServerStatus *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__GetServerStatus(struct soap*, const struct ns__GetServerStatus *, const char*, const char*);

#ifndef soap_write_ns__GetServerStatus
#define soap_write_ns__GetServerStatus(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__GetServerStatus(soap, data),0) || soap_put_ns__GetServerStatus(soap, data, "ns:GetServerStatus", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__GetServerStatus * SOAP_FMAC4 soap_get_ns__GetServerStatus(struct soap*, struct ns__GetServerStatus *, const char*, const char*);

#ifndef soap_read_ns__GetServerStatus
#define soap_read_ns__GetServerStatus(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__GetServerStatus(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct ns__GetServerStatus * SOAP_FMAC2 soap_instantiate_ns__GetServerStatus(struct soap*, int, const char*, const char*, size_t*);

inline struct ns__GetServerStatus * soap_new_ns__GetServerStatus(struct soap *soap, int n = -1) { return soap_instantiate_ns__GetServerStatus(soap, n, NULL, NULL, NULL); }

inline struct ns__GetServerStatus * soap_new_req_ns__GetServerStatus(struct soap *soap) { struct ns__GetServerStatus *_p = soap_instantiate_ns__GetServerStatus(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns__GetServerStatus(soap, _p); } return _p; }

inline struct ns__GetServerStatus * soap_new_set_ns__GetServerStatus(struct soap *soap, char *MsgXml) { struct ns__GetServerStatus *_p = soap_instantiate_ns__GetServerStatus(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns__GetServerStatus(soap, _p); _p->MsgXml = MsgXml; } return _p; }

inline void soap_delete_ns__GetServerStatus(struct soap *soap, struct ns__GetServerStatus *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__GetServerStatus(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__GetServerStatusResponse
#define SOAP_TYPE_ns__GetServerStatusResponse (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__GetServerStatusResponse(struct soap*, struct ns__GetServerStatusResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__GetServerStatusResponse(struct soap*, const struct ns__GetServerStatusResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__GetServerStatusResponse(struct soap*, const char*, int, const struct ns__GetServerStatusResponse *, const char*);
SOAP_FMAC3 struct ns__GetServerStatusResponse * SOAP_FMAC4 soap_in_ns__GetServerStatusResponse(struct soap*, const char*, struct ns__GetServerStatusResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__GetServerStatusResponse(struct soap*, const struct ns__GetServerStatusResponse *, const char*, const char*);

#ifndef soap_write_ns__GetServerStatusResponse
#define soap_write_ns__GetServerStatusResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__GetServerStatusResponse(soap, data),0) || soap_put_ns__GetServerStatusResponse(soap, data, "ns:GetServerStatusResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__GetServerStatusResponse * SOAP_FMAC4 soap_get_ns__GetServerStatusResponse(struct soap*, struct ns__GetServerStatusResponse *, const char*, const char*);

#ifndef soap_read_ns__GetServerStatusResponse
#define soap_read_ns__GetServerStatusResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__GetServerStatusResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct ns__GetServerStatusResponse * SOAP_FMAC2 soap_instantiate_ns__GetServerStatusResponse(struct soap*, int, const char*, const char*, size_t*);

inline struct ns__GetServerStatusResponse * soap_new_ns__GetServerStatusResponse(struct soap *soap, int n = -1) { return soap_instantiate_ns__GetServerStatusResponse(soap, n, NULL, NULL, NULL); }

inline struct ns__GetServerStatusResponse * soap_new_req_ns__GetServerStatusResponse(struct soap *soap) { struct ns__GetServerStatusResponse *_p = soap_instantiate_ns__GetServerStatusResponse(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns__GetServerStatusResponse(soap, _p); } return _p; }

inline struct ns__GetServerStatusResponse * soap_new_set_ns__GetServerStatusResponse(struct soap *soap, char *ResponseXml) { struct ns__GetServerStatusResponse *_p = soap_instantiate_ns__GetServerStatusResponse(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns__GetServerStatusResponse(soap, _p); _p->ResponseXml = ResponseXml; } return _p; }

inline void soap_delete_ns__GetServerStatusResponse(struct soap *soap, struct ns__GetServerStatusResponse *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__GetServerStatusResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__SendMission
#define SOAP_TYPE_ns__SendMission (9)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__SendMission(struct soap*, struct ns__SendMission *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__SendMission(struct soap*, const struct ns__SendMission *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__SendMission(struct soap*, const char*, int, const struct ns__SendMission *, const char*);
SOAP_FMAC3 struct ns__SendMission * SOAP_FMAC4 soap_in_ns__SendMission(struct soap*, const char*, struct ns__SendMission *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__SendMission(struct soap*, const struct ns__SendMission *, const char*, const char*);

#ifndef soap_write_ns__SendMission
#define soap_write_ns__SendMission(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__SendMission(soap, data),0) || soap_put_ns__SendMission(soap, data, "ns:SendMission", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__SendMission * SOAP_FMAC4 soap_get_ns__SendMission(struct soap*, struct ns__SendMission *, const char*, const char*);

#ifndef soap_read_ns__SendMission
#define soap_read_ns__SendMission(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__SendMission(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct ns__SendMission * SOAP_FMAC2 soap_instantiate_ns__SendMission(struct soap*, int, const char*, const char*, size_t*);

inline struct ns__SendMission * soap_new_ns__SendMission(struct soap *soap, int n = -1) { return soap_instantiate_ns__SendMission(soap, n, NULL, NULL, NULL); }

inline struct ns__SendMission * soap_new_req_ns__SendMission(struct soap *soap) { struct ns__SendMission *_p = soap_instantiate_ns__SendMission(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns__SendMission(soap, _p); } return _p; }

inline struct ns__SendMission * soap_new_set_ns__SendMission(struct soap *soap, char *MsgXml) { struct ns__SendMission *_p = soap_instantiate_ns__SendMission(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns__SendMission(soap, _p); _p->MsgXml = MsgXml; } return _p; }

inline void soap_delete_ns__SendMission(struct soap *soap, struct ns__SendMission *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__SendMission(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__SendMissionResponse
#define SOAP_TYPE_ns__SendMissionResponse (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__SendMissionResponse(struct soap*, struct ns__SendMissionResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__SendMissionResponse(struct soap*, const struct ns__SendMissionResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__SendMissionResponse(struct soap*, const char*, int, const struct ns__SendMissionResponse *, const char*);
SOAP_FMAC3 struct ns__SendMissionResponse * SOAP_FMAC4 soap_in_ns__SendMissionResponse(struct soap*, const char*, struct ns__SendMissionResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__SendMissionResponse(struct soap*, const struct ns__SendMissionResponse *, const char*, const char*);

#ifndef soap_write_ns__SendMissionResponse
#define soap_write_ns__SendMissionResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__SendMissionResponse(soap, data),0) || soap_put_ns__SendMissionResponse(soap, data, "ns:SendMissionResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__SendMissionResponse * SOAP_FMAC4 soap_get_ns__SendMissionResponse(struct soap*, struct ns__SendMissionResponse *, const char*, const char*);

#ifndef soap_read_ns__SendMissionResponse
#define soap_read_ns__SendMissionResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__SendMissionResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct ns__SendMissionResponse * SOAP_FMAC2 soap_instantiate_ns__SendMissionResponse(struct soap*, int, const char*, const char*, size_t*);

inline struct ns__SendMissionResponse * soap_new_ns__SendMissionResponse(struct soap *soap, int n = -1) { return soap_instantiate_ns__SendMissionResponse(soap, n, NULL, NULL, NULL); }

inline struct ns__SendMissionResponse * soap_new_req_ns__SendMissionResponse(struct soap *soap) { struct ns__SendMissionResponse *_p = soap_instantiate_ns__SendMissionResponse(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns__SendMissionResponse(soap, _p); } return _p; }

inline struct ns__SendMissionResponse * soap_new_set_ns__SendMissionResponse(struct soap *soap, char *ResponseXml) { struct ns__SendMissionResponse *_p = soap_instantiate_ns__SendMissionResponse(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns__SendMissionResponse(soap, _p); _p->ResponseXml = ResponseXml; } return _p; }

inline void soap_delete_ns__SendMissionResponse(struct soap *soap, struct ns__SendMissionResponse *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__SendMissionResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Reason
#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Reason(soap, data),0) || soap_put_PointerToSOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Reason
#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Detail
#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Detail(soap, data),0) || soap_put_PointerToSOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Detail
#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Code
#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Code(soap, data),0) || soap_put_PointerToSOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Code
#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write__QName
#define soap_write__QName(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize__QName(soap, data),0) || soap_put__QName(soap, data, "byte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef soap_read__QName
#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write_string
#define soap_write_string(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_string(soap, data),0) || soap_put_string(soap, data, "byte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#ifndef soap_read_string
#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

/* End of soapH.h */
