//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by YiRongCarDetectAIO.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_YIRONGCARDETECTAIO_DIALOG   102
#define IDR_MAINFRAME                   128
#define IDD_SHORTCUT                    131
#define IDR_MENU                        133
#define IDD_DEVICE_TREE                 134
#define IDD_PTZ                         135
#define IDD_NORMAL                      136
#define IDB_LOGO                        137
#define IDD_SCREEN                      138
#define IDB_CAR_OPEN                    140
#define IDB_CAR_CLOSE                   141
#define IDB_CAR_MOVE                    142
#define IDB_CAPBMP_OPEN                 144
#define IDB_CAPBMP_MOVE                 145
#define IDB_RECORD_MOVE                 147
#define IDB_MODE1_OPEN                  151
#define IDB_MODE1_CLOSE                 152
#define IDB_MODE1_MOVE                  153
#define IDB_MODE4_OPEN                  154
#define IDB_MODE4_CLOSE                 155
#define IDB_MODE4_MOVE                  156
#define IDB_MODE9_OPEN                  157
#define IDB_MODE9_CLOSE                 158
#define IDB_MODE9_MOVE                  159
#define IDB_MODE16_OPEN                 160
#define IDB_MODE16_CLOSE                161
#define IDB_MODE16_MOVE                 162
#define IDB_RECORD_CLOSE                164
#define IDB_RECORD_OPEN                 165
#define IDB_ALARM_OPEN                  166
#define IDB_ALARM_CLOSE                 167
#define IDB_ALARM_MOVE                  168
#define IDB_PREVIEW_MOVE                169
#define IDB_PREVIEW_OPEN                170
#define IDB_PREVIEW_CLOSE               171
#define IDB_BACK_TREE                   172
#define IDB_BACK_NORMAL                 173
#define IDB_BACK_PTZ                    174
#define IDB_BACK_SHORTCUT               175
#define IDB_PTZ_AUTO_MOVE               176
#define IDB_PTZ_AUTO_OPEN               177
#define IDB_PTZ_AUTO_CLOSE              178
#define IDB_PTZ_DOWN_MOVE               179
#define IDB_PTZ_DOWN_OPEN               180
#define IDB_PTZ_DOWN_CLOSE              181
#define IDB_PTZ_FOCUSSUB_MOVE           182
#define IDB_PTZ_FOCUSADD_OPEN           183
#define IDB_PTZ_FOCUSADD_CLOSE          184
#define IDB_PTZ_FOCUSADD_MOVE           185
#define IDB_PTZ_FOCUSSUB_OPEN           186
#define IDB_PTZ_FOCUSSUB_CLOSE          187
#define IDB_PTZ_IRISSUB_MOVE            188
#define IDB_PTZ_GO_OPEN                 189
#define IDB_PTZ_GO_CLOSE                190
#define IDB_PTZ_GO_MOVE                 191
#define IDB_PTZ_IRISADD_OPEN            192
#define IDB_PTZ_IRISADD_CLOSE           193
#define IDB_PTZ_IRISADD_MOVE            194
#define IDB_PTZ_IRISSUB_OPEN            195
#define IDB_PTZ_IRISSUB_CLOSE           196
#define IDB_PTZ_RIGHT_MOVE              197
#define IDB_PTZ_LEFT_OPEN               198
#define IDB_PTZ_LEFT_CLOSE              199
#define IDB_PTZ_LEFT_MOVE               200
#define IDB_PTZ_LEFTDOWN_OPEN           201
#define IDB_PTZ_LEFTDOWN_CLOSE          202
#define IDB_PTZ_LEFTDOWN_MOVE           203
#define IDB_PTZ_LEFTUP_OPEN             204
#define IDB_PTZ_LEFTUP_CLOSE            205
#define IDB_PTZ_LEFTUP_MOVE             206
#define IDB_PTZ_RIGHT_OPEN              207
#define IDB_PTZ_RIGHT_CLOSE             208
#define IDB_PTZ_SET_MOVE                209
#define IDB_PTZ_RIGHTDOWN_OPEN          210
#define IDB_PTZ_RIGHTDOWN_CLOSE         211
#define IDB_PTZ_RIGHTDOWN_MOVE          212
#define IDB_PTZ_RIGHTUP_OPEN            213
#define IDB_PTZ_RIGHTUP_CLOSE           214
#define IDB_PTZ_RIGHTUP_MOVE            215
#define IDB_PTZ_SET_OPEN                216
#define IDB_PTZ_SET_CLOSE               217
#define IDB_PTZ_SPEEDSUB_MOVE           218
#define IDB_PTZ_SPEEDADD_OPEN           219
#define IDB_PTZ_SPEEDADD_CLOSE          220
#define IDB_PTZ_SPEEDADD_MOVE           221
#define IDB_PTZ_SPEEDSUB_OPEN           222
#define IDB_PTZ_SPEEDSUB_CLOSE          223
#define IDB_PTZ_ZOOMSUB_MOVE            224
#define IDB_PTZ_UP_OPEN                 225
#define IDB_PTZ_UP_CLOSE                226
#define IDB_PTZ_UP_MOVE                 227
#define IDB_PTZ_ZOOMADD_OPEN            228
#define IDB_PTZ_ZOOMADD_CLOSE           229
#define IDB_PTZ_ZOOMADD_MOVE            230
#define IDB_PTZ_ZOOMSUB_OPEN            231
#define IDB_PTZ_ZOOMSUB_CLOSE           232
#define IDB_BACK_MAIN                   233
#define IDD_LOGIN                       235
#define IDB_LOGIN_EXIT                  236
#define IDB_LOGIN_LOCK                  237
#define IDB_LOGIN_IN                    238
#define IDB_LOGIN_OKOUT                 239
#define IDB_LOGIN_CANCELIN              240
#define IDB_LOGIN_CANCELOUT             241
#define IDB_LOGIN_OKIN                  242
#define IDD_OPEN_CLOSE_PREVIEW          243
#define IDB_SETCAR_OPEN                 244
#define IDB_SETCAR_CLOSE                245
#define IDB_SETCAR_MOVE                 246
#define IDD_HISTORY_VIDEO               247
#define IDD_SET_USER                    248
#define IDD_SET_BLACK                   249
#define IDB_LOGIN_MODIFY                250
#define IDD_SET_SYSTEM                  253
#define IDD_WARNNING                    255
#define IDR_MENU_RCTREE                 261
#define IDR_MENU_RCTREE1                262
#define IDD_ADD_DEVICE                  263
#define IDD_DIALOG1                     264
#define IDD_HISTORY_DETECT              267
#define IDD_HISTORY_REPORT              268
#define IDD_SET_CAR                     269
#define IDD_SET_ELECAR                  270
#define IDD_SET_PTZ                     271
#define IDB_SETPTZ_BACK                 272
#define IDD_SET_RECORD                  273
#define IDD_BLACK_INOUT                 275
#define IDB_SCREEN_BACK                 278
#define IDB_NORMAL_RECOGNIZE_CLOSE      279
#define IDB_NORMAL_ALARM_CLOSE          280
#define IDB_NORMAL_ALARM_CLOSEALL       281
#define IDB_NORMAL_CAR_SET              282
#define IDB_NORMAL_CHANNEL              283
#define IDB_NORMAL_PREVIEW_CLOSE        284
#define IDB_NORMAL_PREVIEW_CLOSEALL     285
#define IDB_NORMAL_RECOGNIZE_CLOSEALL   286
#define IDB_NORMAL_RECORD_CLOSE         287
#define IDB_NORMAL_RECORD_CLOSEALL      288
#define IDB_NORMAL_BLACK_SET            289
#define IDB_NORMAL_ALARM_OPEN           290
#define IDB_NORMAL_ALARM_OPENALL        291
#define IDB_NORMAL_PREVIEW_OPENALL      292
#define IDB_NORMAL_RECOGNIZE_OPEN       293
#define IDB_NORMAL_RECOGNIZE_OPENALL    294
#define IDB_NORMAL_HISTORY_ALARM        295
#define IDB_NORMAL_HISTORY_RECOGNIZE    296
#define IDB_NORMAL_HISTORY_VIDEO        297
#define IDB_NORMAL_PREVIEW_OPEN         298
#define IDB_NORMAL_RECORD_OPEN          299
#define IDB_NORMAL_RECORD_OPENALL       300
#define IDB_NORMAL_CAPBMP               301
#define IDB_NORMAL_ALARM_OPENALL_PUSH   309
#define IDB_NORMAL_HISTORY_RECOGNIZE_PUSH 310
#define IDB_NORMAL_RECORD_OPEN_PUSH     311
#define IDB_NORMAL_RECORD_OPENALL_PUSH  312
#define IDB_NORMAL_CAPBMP_PUSH          313
#define IDB_NORMAL_RECOGNIZE_OPEN_PUSH  314
#define IDB_NORMAL_RECOGNIZE_OPENALL_PUSH 315
#define IDB_NORMAL_PREVIEW_OPEN_PUSH    316
#define IDB_NORMAL_PREVIEW_OPENALL_PUSH 317
#define IDB_NORMAL_CHANNEL_PUSH         318
#define IDB_NORMAL_RECOGNIZE_CLOSE_PUSH 319
#define IDB_NORMAL_CAR_SET_PUSH         320
#define IDB_NORMAL_BLACK_SET_PUSH       321
#define IDB_NORMAL_PREVIEW_CLOSE_PUSH   322
#define IDB_NORMAL_RECORD_CLOSE_PUSH    323
#define IDB_NORMAL_ALARM_CLOSE_PUSH     324
#define IDB_NORMAL_RECORD_CLOSEALL_PUSH 325
#define IDB_NORMAL_ALARM_CLOSEALL_PUSH  326
#define IDB_NORMAL_ALARM_OPEN_PUSH      327
#define IDB_NORMAL_HISTORY_ALARM_PUSH   328
#define IDB_NORMAL_HISTORY_VIDEO_PUSH   329
#define IDB_NORMAL_PREVIEW_CLOSEALL_PUSH 330
#define IDB_NORMAL_RECOGNIZE_CLOSEALL_PUSH 331
#define IDB_TAB_NORMAL_CLOSE            332
#define IDB_TAB_NORMAL                  333
#define IDB_TAB_PTZ                     334
#define IDB_TAB_PTZ_CLOSE               335
#define IDB_TAB_TREE                    336
#define IDB_TAB_TREE_CLOSE              337
#define IDD_ANALYSE_FLOWRATE            340
#define IDD_VIDEO_DETECT                347
#define IDB_LOGO_ELECAR                 349
#define IDD_HELP                        350
#define IDC_TAB_MAIN                    1000
#define IDC_BUTTON1                     1001
#define IDC_BUTTON_FILE                 1001
#define IDC_LIST_CAR                    1002
#define IDC_BUTTON_FULL_SCREEN          1003
#define IDC_BUTTON2                     1004
#define IDC_BUTTON_START                1004
#define IDC_BUTTON_STOP                 1005
#define IDC_BUTTON_PAUSE                1005
#define IDC_BUTTON_CLOSE_PREVIEW_ALL    1006
#define IDC_BUTTON_TREE                 1007
#define IDC_TREE_DEVICE                 1008
#define IDC_RIGHT                       1009
#define IDC_BUTTON_CAR                  1010
#define IDC_BUTTON_CAPBMP               1011
#define IDC_BUTTON_SEARCH_ALL           1012
#define IDC_BUTTON_MODE1                1013
#define IDC_BUTTON_MODE4                1014
#define IDC_BUTTON_MODE9                1015
#define IDC_BUTTON_MODE16               1016
#define IDC_BUTTON_PREVIEW              1017
#define IDC_BUTTON_ALARM                1018
#define IDC_BUTTON_RECORD               1019
#define IDC_AUTO                        1020
#define IDC_DOWNLEFT                    1021
#define IDC_DOWN                        1022
#define IDC_DOWNRIGHT                   1023
#define IDC_UPLEFT                      1024
#define IDC_UP                          1025
#define IDC_UPRIGHT                     1026
#define IDC_LEFT                        1027
#define IDC_FOCUS_ADD                   1028
#define IDC_FOCUS_SUB                   1029
#define IDC_IRIS_ADD                    1030
#define IDC_IRIS_SUB                    1031
#define IDC_ZOOM_ADD                    1032
#define IDC_ZOOM_SUB                    1033
#define IDC_BUTTON_SET                  1034
#define IDC_BUTTON_GO                   1035
#define IDC_EDIT_SET                    1037
#define IDC_SPEED_SUB                   1038
#define IDC_SPEED_ADD                   1039
#define IDC_EDIT_SPEED                  1040
#define IDC_STATIC_PRINTF               1041
#define IDC_COMBO1                      1042
#define IDC_COMBO_STREAM                1043
#define IDC_BUTTON5                     1044
#define IDC_BUTTON_SPEED                1044
#define IDC_BUTTON6                     1045
#define IDC_BUTTON8                     1047
#define IDC_BUTTON9                     1048
#define IDC_BUTTON10                    1049
#define IDC_BUTTON11                    1050
#define IDC_BUTTON12                    1051
#define IDC_BUTTON13                    1052
#define IDC_BUTTON14                    1053
#define IDC_BUTTON15                    1054
#define IDC_BUTTON16                    1055
#define IDC_BUTTON_HISTORY_VIDEO        1056
#define IDC_BUTTON18                    1057
#define IDC_BUTTON19                    1058
#define IDC_BUTTON20                    1059
#define IDC_BUTTON21                    1060
#define IDC_EDIT_USER                   1064
#define IDC_EDIT_PSW                    1065
#define IDC_CHECK                       1066
#define IDC_SET_CAR                     1067
#define IDC_BUTTON_CLOSE                1068
#define IDC_BUTTON_OPEN                 1069
#define IDC_EDIT_NAME                   1070
#define IDC_EDIT_IP                     1071
#define IDC_CHECK_TIME                  1073
#define IDC_DATETIMEPICKER_STARTMON     1074
#define IDC_DATETIMEPICKER_ENDMON       1075
#define IDC_DATETIMEPICKER_STARTHOUR    1076
#define IDC_DATETIMEPICKER_ENDHOUR      1077
#define IDC_CHECK_WEEK                  1078
#define IDC_BUTTON_SEARCH               1079
#define IDC_BUTTON_PLAY                 1080
#define IDC_BUTTON_FIRST                1082
#define IDC_EDIT_PAGE                   1083
#define IDC_BUTTON_JUMP                 1084
#define IDC_STATIC_INFO                 1085
#define IDC_BUTTON_PREVIOUS             1086
#define IDC_BUTTON_NEXT                 1087
#define IDC_BUTTON_LAST                 1088
#define IDC_EDIT_USER_PSWAGAIN          1089
#define IDC_BUTTON_USER_DELETE          1090
#define IDC_CHECK_USER_CAPBMP           1092
#define IDC_CHECK_USER_PREVIEW          1093
#define IDC_CHECK_USER_RECORDSET        1094
#define IDC_CHECK_USER_BLACKSET         1095
#define IDC_CHECK_USER_DETECTSET        1096
#define IDC_CHECK_USER_DETECT           1097
#define IDC_CHECK_USER_HISTORYVIDEO     1099
#define IDC_BUTTON_USER_ADD             1100
#define IDC_CHECK_USER_HISTORYDETECT    1102
#define IDC_CHECK_USER_HISTORYALARM     1103
#define IDC_CHECK_USER_HISTORYREPORT    1104
#define IDC_BUTTON_USER_MODIFY          1105
#define IDC_CHECK_USER_DEVICE           1106
#define IDC_CHECK_ALL                   1107
#define IDC_BUTTON_BLACK_CLEAN          1108
#define IDC_EDIT_BLACK_PLATE            1109
#define IDC_EDIT_BLACK_NAME             1110
#define IDC_EDIT_BLACK_PHONE            1111
#define IDC_EDIT_BLACK_BRAND            1112
#define IDC_EDIT_OTHER                  1113
#define IDC_BUTTON_BLACK_ADD            1114
#define IDC_BUTTON_BLACK_MODIFY         1115
#define IDC_BUTTON_BLACK_DELETE         1116
#define IDC_BUTTON_BLACK_INPUT          1117
#define IDC_BUTTON_BLACK_OUPUT          1118
#define IDC_STATIC_NEWPSW               1119
#define IDC_STATIC_NEWPSW_AGAIN         1120
#define IDC_CHECK_ALARM_PIC             1122
#define IDC_CHECK_ALARM_WAV             1123
#define IDC_EDIT_ALARM_WAV              1124
#define IDC_BUTTON_ALARM_WAV            1125
#define IDC_EDIT_TIME                   1126
#define IDC_EDIT_RECORD_DIR             1127
#define IDC_BUTTON_RECORD_DIR           1128
#define IDC_COMBO_RECORDFULL            1129
#define IDC_CHECK_FTP                   1130
#define IDC_EDIT_DETECT_DIR             1131
#define IDC_BUTTON_DETECT_DIR           1132
#define IDC_EDIT_CAPBMP_DIR             1133
#define IDC_BUTTON_CAPBMP_DIR           1134
#define IDC_EDIT_FTP_IPADDR             1135
#define IDC_EDIT_FTP_PORT               1136
#define IDC_EDIT_FTP_USER               1137
#define IDC_EDIT_FTP_PSW                1138
#define IDC_EDIT_FTP_PATH               1139
#define IDC_EDIT_HAIKANG_PATH           1146
#define IDC_BUTTON_HAIKANG_PATH         1147
#define IDC_EDIT_DAHUA_PATH             1149
#define IDC_BUTTON_DAHUA_PATH           1150
#define IDC_EDIT_YAAN_PATH              1153
#define IDC_BUTTON_YAAN_PATH            1154
#define IDC_EDIT_CAM_NAME               1209
#define IDC_EDIT_CAM_IPADDR             1210
#define IDC_EDIT_CAM_PORT               1211
#define IDC_EDIT_CAM_USER               1212
#define IDC_EDIT_CAM_PSW                1213
#define IDC_EDIT_AREA                   1216
#define IDC_EDIT_ADDAREA                1217
#define IDC_COMBO_CAMAREA               1218
#define IDC_BUTTON_ADDAREA              1219
#define IDC_COMBO_CAMVENDER             1220
#define IDC_EDIT3                       1240
#define IDC_STATIC_ADDAREA_NOTE         1245
#define IDC_COMBO_DIRECTION             1251
#define IDC_COMBO_PLATECOLOR            1252
#define IDC_EDIT_RELIABILITY            1253
#define IDC_CHECK1                      1254
#define IDC_CHECK2                      1255
#define IDC_CHECK3                      1256
#define IDC_CHECK4                      1257
#define IDC_CHECK5                      1258
#define IDC_CHECK6                      1259
#define IDC_CHECK7                      1260
#define IDC_CHECK8                      1261
#define IDC_CHECK9                      1262
#define IDC_CHECK10                     1263
#define IDC_CHECK11                     1264
#define IDC_CHECK12                     1265
#define IDC_CHECK13                     1266
#define IDC_CHECK14                     1267
#define IDC_CHECK15                     1268
#define IDC_CHECK16                     1269
#define IDC_CHECK17                     1270
#define IDC_CHECK18                     1271
#define IDC_CHECK19                     1272
#define IDC_CHECK20                     1273
#define IDC_CHECK21                     1274
#define IDC_CHECK22                     1275
#define IDC_CHECK23                     1276
#define IDC_CHECK24                     1277
#define IDC_CHECK25                     1278
#define IDC_CHECK26                     1279
#define IDC_CHECK27                     1280
#define IDC_CHECK28                     1281
#define IDC_CHECK29                     1282
#define IDC_CHECK30                     1283
#define IDC_CHECK31                     1284
#define IDC_CHECK32                     1285
#define IDC_CHECK_DESKEW                1286
#define IDC_CHECK_CAR_COLOR             1287
#define IDC_CHECK_OUTPUT_RECT           1288
#define IDC_EDIT_JPG_QUALITY            1289
#define IDC_EDIT_MIN_WIDTH              1290
#define IDC_EDIT_MAX_WIDTH              1291
#define IDC_EDIT_LEFT                   1292
#define IDC_EDIT_UP                     1293
#define IDC_EDIT_RIGHT                  1294
#define IDC_EDIT_DOWN                   1295
#define IDC_DEFAULT_PROVINCE            1296
#define IDC_CHECK_ADMIN                 1297
#define IDC_STATIC_AEAR                 1301
#define IDC_STATIC_CAM                  1302
#define IDC_BUTTON_DELETE               1302
#define IDC_STATIC_CAM2                 1303
#define IDC_BUTTON_MODIFY               1303
#define IDC_STATIC_IP                   1303
#define IDC_BUTTON_ADD                  1304
#define IDC_BUTTON_DISABLE              1305
#define IDC_BUTTON_ENABLE               1306
#define IDC_COMBO_AREA                  1307
#define IDC_COMBO_CAM                   1308
#define IDC_CHECK_ENABLE                1309
#define IDC_CHECK_DATE                  1310
#define IDC_CHECK_EVERYDAY              1311
#define IDC_PROGRESS                    1312
#define IDC_STATIC_WINNO                1314
#define IDC_STATIC_USER                 1315
#define IDC_STATIC_PSW                  1316
#define IDC_BUTTON_PTZ                  1317
#define IDC_STATIC_RECT                 1318
#define IDC_CHECK_SAVENET               1320
#define IDC_STATIC_VIDEO                1322
#define IDC_BUTTON_OPENCHANNEL          1323
#define IDC_BUTTON_NORMAL               1324
#define IDC_BUTTON_SEARCH_SINGLE        1325
#define IDC_BUTTON4                     1326
#define IDC_BUTTON_STOP2                1326
#define IDC_COMBO_SCREEN                1327
#define IDC_COMBO_WINNO                 1328
#define IDC_COMBO2                      1329
#define IDC_COMBO3                      1330
#define IDC_COMBO_PLATETYPE             1331
#define IDC_COMBO_ENDWEEK               1332
#define IDC_BUTTON_OPEN_PREVIEW         1333
#define IDC_COMBO_CARCOLOR              1334
#define IDC_COMBO4                      1335
#define IDC_COMBO_STARTWEEK             1336
#define IDC_BUTTON_OPEN_PREVIEW_ALL     1337
#define IDC_BUTTON7                     1338
#define IDC_BUTTON_CUTPIC               1338
#define IDC_BUTTON_OPEN_DETECT          1339
#define IDC_BUTTON_OPEN_DETECT_ALL      1340
#define IDC_BUTTON_CLOSE_DETECT_ALL     1341
#define IDC_BUTTON_OPEN_RECORD          1342
#define IDC_BUTTON_OPEN_RECORD_ALL      1345
#define IDC_BUTTON_CLOSE_RECORD_ALL     1346
#define IDC_BUTTON_OPEN_ALARM           1347
#define IDC_BUTTON_OPEN_ALARM_ALL       1348
#define IDC_BUTTON_CLOSE_ALARM_ALL      1349
#define IDC_BUTTON17                    1350
#define IDC_BUTTON_HISTORY_DETECT       1351
#define IDC_BUTTON_HISTORY_ALARM        1352
#define IDC_BUTTON_SET_CAR              1353
#define IDC_BUTTON_SET_BLACK            1354
#define IDC_LIST                        1355
#define IDC_EDIT_NEWPSW                 1356
#define IDC_CHECK_USER_RECORD           1357
#define IDC_EDIT_NEWPSW_AGAIN           1358
#define IDC_CHECK_USER_PTZ              1359
#define IDC_CHECK_USER_SYSTEMSET        1360
#define IDC_DATETIMEPICKER_DAY          1361
#define IDC_EDIT_USER_PSW               1362
#define IDC_BUTTON_DELETEALL            1363
#define IDC_STATIC_WARNTXT              1364
#define IDC_EDIT_PLATE                  1365
#define IDC_STATIC_FTP                  1370
#define IDC_STATIC_FTP_IP               1371
#define IDC_STATIC_FTP_PORT             1372
#define IDC_STATIC_FTP_USER             1373
#define IDC_STATIC_FTP_PSW              1374
#define IDC_STATIC_FTP_PATH             1375
#define IDC_STATIC_CAMIP                1376
#define IDC_EDIT_FILE                   1379
#define IDC_CHECK_WRITE_DB              1380
#define IDC_SLIDER                      1381
#define IDC_STATIC_STARTTIME            1384
#define IDC_STATIC_ENDTIME              1385
#define IDC_STATIC_PLAYWIN              1386
#define IDC_STATIC_USERNAME             1388
#define IDC_STATIC_TIME                 1390
#define ID_MENUITEM_LOGIN_LOCK          32771
#define ID_MENUITEM_LOGIN_IN            32772
#define ID_MENUITEM_LOGIN_EXIT          32773
#define ID_MENUITEM_CAPBMP              32774
#define ID_MENUITEM_1MODE               32776
#define ID_MENUITEM_9MODE               32778
#define ID_MENUITEM_16MODE              32779
#define ID_MENUITEM_4MODE               32780
#define ID_MENUITEM_PREVIEW             32781
#define ID_MENUITEM_DETECT              32782
#define ID_MENUITEM_ALARM               32783
#define ID_MENUITEM_RECORD              32784
#define ID_MENUITEM_SYSTEM_REPORT       32785
#define ID_MENUITEM_HISTORY_CAR         32786
#define ID_MENUITEM_HISTORY_ALARM       32787
#define ID_MENUITEM_BLACK_IN            32788
#define ID_MENUITEM_BLACK_OUT           32789
#define ID_MENUITEM_SET_USER            32790
#define ID_MENUITEM_SET_SYSTEM          32791
#define ID_MENUITEM_SET_SYSTEM_IN       32792
#define ID_MENUITEM_SET_SYSTEM_OUT      32793
#define ID_MENUITEM_SET_CAR             32795
#define ID_MENUITEM_SET_BLACK           32796
#define ID_MENUITEM_SET_PTZ             32797
#define ID_MENUITEM_CARSTREAM           32798
#define ID_MENUITEM_ABOUT               32799
#define ID_MENUITEM_HELP                32800
#define ID_MENUITEM_HISTORY_VIDEO       32801
#define ID_MENUITEM_SET_RECORD          32802
#define ID_MENUITEM_LOGIN_MODIFY        32803
#define ID_MENUITEM_UPDATE              32809
#define ID_MENUITEM_EDITDEVICE          32810
#define ID_MENUITEM_DELETEDEVICE        32811
#define ID_MENUITEM_ADDDEVICE           32812
#define ID_MENUITEM_DELETEAREA          32816
#define ID_MENUITEM_VIDEODETECT         32818

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        351
#define _APS_NEXT_COMMAND_VALUE         32819
#define _APS_NEXT_CONTROL_VALUE         1391
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
