// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "luserparamx.h"

/////////////////////////////////////////////////////////////////////////////
// CLUSerParamX

IMPLEMENT_DYNCREATE(CLUSerParamX, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CLUSerParamX properties

/////////////////////////////////////////////////////////////////////////////
// CLUSerParamX operations

long CLUSerParamX::ShowParamPage(LPCTSTR sername, LPCTSTR serurl, short serport, LPCTSTR username, LPCTSTR password)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_I2 VTS_BSTR VTS_BSTR;
	InvokeHelper(0x1, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		sername, serurl, serport, username, password);
	return result;
}
